spring.application.name=shopez

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:shopezdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# CTF flag — injected via environment variable at runtime
app.ctf-flag=${S5_FLAG:flag{1D0R_0rd3r_l34k_sh0p3z!}}
